限定pip版本
Rock-Candy-Tea/hexo-circle-of-friends pull request #144
Opened 2024-06-27 21:25 UTC by LanYunDev

解决pip版本在24.1时安装uvicorn依赖的报错

DEPRECATION: uvicorn 0.14.0 has a non-standard dependency specifier click>=7.*. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of uvicorn or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

2024-06-29 00:22 UTC, Gan1Ser commented
正解

2024-06-29 06:44 UTC, thun888 commented
感谢

2024-06-30 03:13 UTC, Barry-Flynn commented
嘿哥们，我按照你提交的添加那两行之后，Vercel 报错 `Deployment has failed`，可以帮我看一下吗

2024-06-30 03:20 UTC, LanYunDev commented
我只限定了GitHub action中的pip版本,没遇到你这个vercel报错
<img width="1284" alt="image" src="https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/95263282/8812980a-897c-4867-984c-2172e910110c">

2024-06-30 03:24 UTC, LanYunDev commented
> 嘿哥们，我按照你提交的添加那两行之后，Vercel 报错 `Deployment has failed`，可以帮我看一下吗
> 
> [Barry-Flynn@5181a2c](https://github.com/Barry-Flynn/hexo-circle-of-friends/commit/5181a2c2ce5444910e2e98bc3f5178b648a15260)

看了下你的vercel[日志](https://vercel.com/barryflynns-projects/hexo-circle-of-friends/7r4wkjpaMj3ZRQihkeCmBvMMQHy5)
<img width="1324" alt="image" src="https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/95263282/17f7e057-4096-4669-b014-aa5047c88bb7">
版本问题,限制pip版本就行了.

2024-06-30 03:27 UTC, LanYunDev commented
https://github.com/Barry-Flynn/hexo-circle-of-friends/blob/main/requirements.txt
添加一项`pip==24.0`试试看?我没试过,不知道可行不.

2024-06-30 03:35 UTC, Barry-Flynn commented
> pip==24.0

感谢回复，但似乎还是报错

https://github.com/Barry-Flynn/hexo-circle-of-friends/commit/eebe01645e30b890324837caeb663b43efbe4a77

https://vercel.com/barryflynns-projects/hexo-circle-of-friends/B1JpyivcL1LMQMztjHrNBWp5fZuW?filter=errors

2024-06-30 03:35 UTC, LanYunDev commented
@Barry-Flynn 看了下,你那个github action没问题了,不清楚你的vercel为什么还是报错,你直接fork我的版本 https://github.com/LanYunDev/hexo-circle-of-friends/tree/fork 再根据你的配置重新部署吧

2024-06-30 07:41 UTC, CCKNBC approved these changes
GitHub Actions 运行错误，请根据文件变更修改工作流，或拉取新版本

2024-06-30 09:34 UTC, CCKNBC requested changes
依赖问题，锁定Node(16)，否则会使用python312 pip 24.0 暂时正常，但这不是长久之计
![image](https://github.com/Rock-Candy-Tea/hexo-circle-of-friends/assets/62093618/7c55104a-693f-47d1-a966-0d3f16b7c02a)

2024-06-30 11:46 UTC, LanYunDev commented
@Barry-Flynn 我后来复现了你的问题,最新版fork已修复

2024-06-30 11:46 UTC, LanYunDev commented
@CCKNBC 通过更新依赖版本,已经解决报错问题,无需指定pip版本

2024-06-30 12:01 UTC, CCKNBC approved these changes
OK，感谢

2024-06-30 12:05 UTC, merged

2024-07-01 06:38 UTC, cworld1 commented
所以为什么我更新就被拒🥲🥲

2024-07-01 15:14 UTC, CCKNBC commented
> 所以为什么我的更新pr就被拒🥲🥲

可能开发者觉得能用就别破坏它